theme: jekyll-theme-minimal
title: my portfolio
description: welcome to my portfolio! my name is emily, i am a junior at rutgers university majoring in computer science and french, and here you will find projects that i have worked on.

