theme: jekyll-theme-hacker
title: My Portfolio
description: Welcome to my portfolio! My name is Emily, I am a Junior at Rutgers University majoring in Computer Science and French, and here you will find projects that I have worked on.

