theme: jekyll-theme-minimal
title: my portfolio
description: welcome to my portfolio! my name is emily, and i am a senior at rutgers university majoring in computer science and french. Here you will find projects that i have worked on.

